### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-rails-model-validations#2]
BOOM
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://dry-depths-9791.herokuapp.com/books) and meets the following [project](http://lansingcodelab.com/lessons/rails-model-validations/1) criteria:
- [x] Every attribute on your model has reasonable validations to prevent bad data from being entered by users

**Comment by chrisvfritz** [comment]
Some books do legitimately have the same title. For example, I think I've read a few books called _The Future of Education_. :smiley: So I'm not sure this validation actually makes sense for your model:

``` ruby
validates :title, uniqueness: {
  message: "cannot be the same as an existing book title"
}
```

BUT! If you had an `author` attribute for example, it might make sense to have a validation like this:

``` ruby
validates :title, uniqueness: {
  scope: :author,
  message: "cannot be the same as an existing book title with the same author"
}
```

That validates that _if the `author` is the same_, then the `title` must be unique to that author. For the sake of simplicity in this project though, I would simply remove that validation.

**Comment by KatieMFritz** [comment]
@chrisvfritz Okay, removed!

**Comment by chrisvfritz** [comment]
:shipit:
